vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            # alias qui nous permet d'accéder à nos image depuis le navigateur
            uri_prefix: '%upload_directory%'
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #mappings:
    #    products:
    #        uri_prefix: /image/products
    #        upload_destination: '%kernel.project_dir%/public/image/products'
